@startuml erd
!include tables.pu

users ||-u-o{ address
users ||-l-o{ roles
users ||-r-|| wallets
users ||-d-o{ supplies
users ||-d-o{ payments
users ||-d-o{ orders
users ||-d-o{ deliveries

supplies ||-|| products
products ||-|| orders
orders ||--|| payments
orders ||-|| deliveries

@enduml
